language: node_js
node_js:
- '8'
- '7'
before_script:
- npm install mocha -g
- sleep 15
- psql -c 'create database travis_ci_test;' -U postgres
- knex migrate:latest --env test
script:
- mocha
services:
- postgresql
